# Generated by Django 2.1.2 on 2018-12-20 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField(verbose_name='Data Inicio')),
                ('dataFim', models.DateField(verbose_name='Data Data Fim')),
                ('atendimento', models.IntegerField(verbose_name='Numero Atendimento')),
            ],
        ),
        migrations.CreateModel(
            name='DadosSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateField(verbose_name='Data Hora')),
                ('dadosSensor01', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor  1')),
                ('dadosSensor02', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor  2')),
                ('dadosSensor03', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor  3')),
                ('dadosSensor04', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor  4')),
                ('dadosSensor05', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor  5')),
                ('dadosSensor06', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor  6')),
                ('dadosSensor07', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor  7')),
                ('dadosSensor08', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor  8')),
                ('dadosSensor09', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor  9')),
                ('dadosSensor10', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 10')),
                ('dadosSensor11', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 11')),
                ('dadosSensor12', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 12')),
                ('dadosSensor13', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 13')),
                ('dadosSensor14', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 14')),
                ('dadosSensor15', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 15')),
                ('dadosSensor16', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 16')),
                ('dadosSensor17', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 17')),
                ('dadosSensor18', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 18')),
                ('dadosSensor19', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 19')),
                ('dadosSensor20', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 20')),
                ('dadosSensor21', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 21')),
                ('dadosSensor22', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 22')),
                ('dadosSensor23', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 23')),
                ('dadosSensor24', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 24')),
                ('dadosSensor25', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 25')),
                ('dadosSensor26', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 26')),
                ('dadosSensor27', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 27')),
                ('dadosSensor28', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 28')),
                ('dadosSensor29', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 29')),
                ('dadosSensor30', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 30')),
                ('dadosSensor31', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 31')),
                ('dadosSensor32', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 32')),
                ('dadosSensor33', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 33')),
                ('dadosSensor34', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 34')),
                ('dadosSensor35', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 35')),
                ('dadosSensor36', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 36')),
                ('dadosSensor37', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 37')),
                ('dadosSensor38', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 38')),
                ('dadosSensor39', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 39')),
                ('dadosSensor40', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 40')),
                ('dadosSensor41', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 41')),
                ('dadosSensor42', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 42')),
                ('dadosSensor43', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 43')),
                ('dadosSensor44', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 44')),
                ('dadosSensor45', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 45')),
                ('dadosSensor46', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 46')),
                ('dadosSensor47', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 47')),
                ('dadosSensor48', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 48')),
                ('dadosSensor49', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 49')),
                ('dadosSensor50', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 50')),
                ('dadosSensor51', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 51')),
                ('dadosSensor52', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 52')),
                ('dadosSensor53', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 53')),
                ('dadosSensor54', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 54')),
                ('dadosSensor55', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 55')),
                ('dadosSensor56', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor 56')),
                ('idAvaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dadosAvaliacao', to='manta.Avaliacao', verbose_name='Avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome do Paciente')),
                ('dataNascimento', models.DateField(verbose_name='Data Nascimento')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='idPaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='manta.Paciente', verbose_name='Paciente'),
        ),
    ]
